version: "3.8"

services:
  frontend:
    container_name: portofolio-se
    image: portofolio-se/frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6969:80"
    restart: always
